repos:
  - repo: https://github.com/PyCQA/flake8
    rev: a2b02b8
    hooks:
      - id: flake8
        args: ["--max-line-length=250"]

  # - repo: https://github.com/psf/black
  #   rev: 6310a40
  #   hooks:
  #     - id: black
  #       args: ["--line-length=200"]

  - repo: https://github.com/PyCQA/isort
    rev: fd5e3d6
    hooks:
      - id: isort
