version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      # Install dependencies
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
