# Generated by Django 4.1.7 on 2023-08-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_customuser_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='topics',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
