# Generated by Django 4.1.7 on 2023-08-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_customuser_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='topics',
        ),
        migrations.AddField(
            model_name='customuser',
            name='topics',
            field=models.ManyToManyField(blank=True, to='User.topic'),
        ),
    ]
