# Generated by Django 4.2.3 on 2023-07-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Authors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Papers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("publication_date", models.DateField()),
                ("abstract", models.TextField()),
                ("domain", models.CharField(max_length=50)),
                ("pdf_url", models.URLField()),
                ("conference_journal", models.CharField(max_length=100)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("authors", models.ManyToManyField(to="Paper.authors")),
                ("references", models.ManyToManyField(blank=True, to="Paper.papers")),
            ],
        ),
    ]
